
services:

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init/postgres:/postgres:rw
      - ./storage/postgres:/var/lib/postgresql/data:rw
    env_file: envs/postgres.env
    networks:
      - backend-vadmin-net

  backend-vadmin:
    container_name: backend
    platform: linux/amd64
    build: vadmin-backend
    links:
      - postgres:postgres
    volumes:
      - ./vadmin-backend/vadmin:/opt/project:rw
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend-vadmin-net
    env_file: vadmin-backend/vadmin.env

  frontend-vadmin:
    platform: linux/amd64
    build: vadmin-frontend
    links:
      - backend-vadmin:backend-vadmin
    ports:
      - "3000:3000"
    volumes:
      - ./vadmin-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend-vadmin-net
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true

networks:
  backend-vadmin-net:
  frontend-vadmin-net:
